// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;

namespace XTranslate.iOS
{
    public partial class MainTabBarController : UITabBarController
    {
        public MainTabBarController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }

        public override void ViewWillLayoutSubviews()
        {
            foreach (var tabBarItem in this.TabBar.Items)
            {
                tabBarItem.ImageInsets = new UIEdgeInsets(6, 0, 0, 0);
            }


            base.ViewWillLayoutSubviews();
        }

    }
}
