using System;
using System.Collections.Generic;

namespace XTranslate
{
    public static partial class Help
    {
        public static class Languages
        {
            public static readonly string DefaultLanguageCode = "es";

            public static List<string> Languages = new List<string>
            {
                "Afrikaans",
                "Arabic",
                "Bosnian (Latin)",
                "Bulgarian",
                "Catalan",
                "Chinese Simplified",
                "Chinese Traditional",
                "Croatian",
                "Czech",
                "Danish",
                "Dutch",
                "English",
                "Estonian",
                "Finnish",
                "French",
                "German",
                "Greek",
                "Haitian Creole",
                "Hebrew",
                "Hindi",
                "Hmong Daw",
                "Hungarian",
                "Indonesian",
                "Italian",
                "Japanese",
                "Kiswahili",
                "Klingon",
                "Klingon (pIqaD)",
                "Korean",
                "Latvian",
                "Lithuanian",
                "Malay",
                "Maltese",
                "Norwegian",
                "Persian",
                "Polish",
                "Portuguese",
                "Querétaro Otomi",
                "Romanian",
                "Russian",
                "Serbian (Cyrillic)",
                "Serbian (Latin)",
                "Slovak",
                "Slovenian",
                "Spanish",
                "Swedish",
                "Thai",
                "Turkish",
                "Ukrainian",
                "Urdu",
                "Vietnamese",
                "Welsh",
                "Yucatec Maya"
            };

            public static Dictionary<string, string> LanguageCodes = new Dictionary<string, string>
            {
                { "Afrikaans", "af" },
                { "Arabic", "ar" },
                { "Bosnian (Latin)", "bs-Latn" },
                { "Bulgarian", "bg" },
                { "Catalan", "ca" },
                { "Chinese Simplified", "zh-CHS" },
                { "Chinese Traditional", "zh-CHT" },
                { "Croatian", "hr" },
                { "Czech", "cs" },
                { "Danish", "da" },
                { "Dutch", "nl" },
                { "English", "en" },
                { "Estonian", "et" },
                { "Finnish", "fi" },
                { "French", "fr" },
                { "German", "de" },
                { "Greek", "el" },
                { "Haitian Creole", "ht" },
                { "Hebrew", "he" },
                { "Hindi", "hi" },
                { "Hmong Daw", "mww" },
                { "Hungarian", "hu" },
                { "Indonesian", "id" },
                { "Italian", "it" },
                { "Japanese", "ja" },
                { "Kiswahili", "sw" },
                { "Klingon", "tlh" },
                { "Klingon (pIqaD)", "tlh-Qaak" },
                { "Korean", "ko" },
                { "Latvian", "lv" },
                { "Lithuanian", "lt" },
                { "Malay", "ms" },
                { "Maltese", "mt" },
                { "Norwegian", "no" },
                { "Persian", "fa" },
                { "Polish", "pl" },
                { "Portuguese", "pt" },
                { "Querétaro Otomi", "otq" },
                { "Romanian", "ro" },
                { "Russian", "ru" },
                { "Serbian (Cyrillic)", "sr-Cyrl" },
                { "Serbian (Latin)", "sr-Latn" },
                { "Slovak", "sk" },
                { "Slovenian", "sl" },
                { "Spanish", "es" },
                { "Swedish", "sv" },
                { "Thai", "th" },
                { "Turkish", "tr" },
                { "Ukrainian", "uk" },
                { "Urdu", "ur" },
                { "Vietnamese", "vi" },
                { "Welsh", "cy" },
                { "Yucatec Maya", "yua" }
            };
        }
    }
}
