// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XTranslate.iOS
{
	public partial class IndicatorView : UIView
	{
		public IndicatorView (IntPtr handle) : base (handle)
		{
		}
	}
}
